---
- name: Looking for Location ID
  ansible.builtin.uri:
    url: "https://{{ global_registration_capsule }}:{{ global_registration_port }}/api/locations"
    user: "{{ global_registration_username }}"
    password: "{{ global_registration_password }}"
    force_basic_auth: "{{ global_registration_force_basic_auth }}"
    validate_certs: "{{ global_registration_validate_certs }}"
    method: "GET"
    body_format: json
    body:
      search: name="{{ global_registration_location }}"
    status_code: 200
  register: global_registration_location_result
  when: global_registration_location_id is not defined

- name: Checks if the location was found
  ansible.builtin.debug:
    msg: "This task fails if the location was not found."
  failed_when: global_registration_location_result.json.results | length == 0

- name: Set Location ID if exists
  ansible.builtin.set_fact:
    global_registration_location_id: "{{ global_registration_location_result.json.results[0].id }}"
  when: global_registration_location_result.json.results | length > 0
